name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv (official action)
        uses: astral-sh/setup-uv@v1

      - name: Create project venv
        run: uv venv

      - name: Install pytest as a tool
        run: uv tool install pytest
      
      - name: Run tests
        run: uv run pytest -q
