name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv (official action)
        uses: astral-sh/setup-uv@v1

      - name: Create project venv
        run: uv venv

      - name: Enter virtual environment (Windows)
        if: runner.os == 'Windows'
        run: .\.venv\Scripts\activate.ps1

      - name: Enter virtual environment (Linux)
        if: runner.os == 'Linux'
        run: source ./.venv/bin/activate
      
      - name: Run tests
        run: uv run pytest -q
