name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Setup uv (official action)
        uses: astral-sh/setup-uv@v1

      - name: Create project venv
        run: uv venv

      - name: Run tests on Linux
        if: runner.os == 'Linux'
        run: ./.venv/bin/python -m pytest -q

      - name: Run tests on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: .\.venv\Scripts\pytest.exe -q
