name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python_version: ['3.8', '3.9', '3.11', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Setup uv (official action)
        uses: astral-sh/setup-uv@v1

      - name: Create project venv
        run: uv venv
      
      - name: Run tests
        run: uv run pytest -q
